name: Tests
on:
  push:
    paths:
      - Makefile
      - src/*
      - '.github/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Install dependencies
        run: sudo apt-get install -y libfuse3-dev pkgconf clang-tools

      - name: Compile
        run: make

      - name: Run tests
        run: bin/tests
