name: Tests
on:
  push:
    paths:
      - Makefile
      - src/*

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Compile
        run: make bin/tests

      - name: Run tests
        run: bin/tests
